### ISSUE TITLE
Shows connected but never registers anything.

### ISSUE THREAD

**Issue by Choppra** [OpenSkyPlus/OpenSkyPlus#1] opened 2024-04-16 03:10 UTC
Hi there, having a issue.  I'm a new users but knowledable about SIM and setup and computers.

I am running in Direct Mode with a secondary dedicated Wifi Adapter.

All lights show green, GS Pro Connection API Windows shows Connected and Ready.  When you swing, it just doesn't register anything.  I check skytrak while leaving the range open and the shots dont register.

I've also noticed this same behavior happens if I run Skytrak with the OpenSkyPlus addon WITHOUT gs pro running.  I go through my practice routine but eventually it will just stop registering shots completely but all lights are green and the red dot is visible on my mat.

If I restart skytrak without your custom addon, it works just fine, no issues.

**Comment by Phil1972** [comment] 2024-04-26 00:54
I have the same behavior, have to restart de device though to have readings back.  There is something that is not right about the plugin, i suspect that the device does not like a command and gets into a mode where it needs to be restarted

**Comment by OpenSkyPlus** [comment] 2024-05-05 13:51
Can you paste a copy of your OpenSkyPlus log in here when it stops registering shots?

**Comment by pa-tempus** [comment] 2024-05-05 19:21
> Can you paste a copy of your OpenSkyPlus log in here when it stops registering shots?

Does it log to a file or bring up the console and copy paste?

**Comment by Choppra** [comment] 2024-05-05 19:57
@OpenSkyPlus does it log to a file or do you want it from the OpenSkyPlus console? If you want it from the console, I will tell you that it goes blank when this starts happening.  I noticed that the last time I checked.  I can try to replicate it again.

**Comment by Choppra** [comment] 2024-05-05 23:07
I will set the logging to debug mode.

**Comment by Choppra** [comment] 2024-05-08 13:14
https://gist.github.com/Choppra/1d2e3a5217b9e3d8ee1e004d8ef200d7 - comment at the top explains when it happens.

After this, on the next tee, it could not get it to register my drive.  Without timestamping its hard to see when things occured but i feel like this isn't going to tell you too much.

After failing to drive and then eventually it was able to, the next few shots didn't register as well.

https://gist.github.com/Choppra/5cb3123cf674b09ae139d4f3a28ab583 (same log file but extended).

@OpenSkyPlus

**Comment by Phil1972** [comment] 2024-05-08 15:18
I cannot create a branch since I do not have the permission for the moment, waiting for @OpenSkyPlus to give me access.  But in my changes, I also put timestamps in the log entries so that it is easier to follow and establish a timeline to report problems

**Comment by OpenSkyPlus** [comment] 2024-05-25 13:20
@Phil1972 you should have access to submit PRs now. Did you figure out what was causing this behavior?

**Comment by OpenSkyPlus** [comment] 2024-05-25 13:25
@Choppra I looked at your log and it looks like the plugin is working as intended. The very last shot didn't get sent to GSPro because it looked like a mishit, but everything else seems to be tracking properly.

There is an issue with the GSPro API where if the connection is lost, you cannot reconnect to it without closing the connector and reopening it (then letting OSP automatically reconnect). It's a bug with GSPro and it has been driving me nuts and there is no support or documentation on the GSPro side. It accepts the connection, but anything you send to the API just gets swallowed and nothing happens on the app. Plus, there is no way for OSP to know because the API happily receives the data, just does nothing with it.

If anyone has more experience with the GSPro API and knows how to get around this, we can fix it, but otherwise there isn't much we can do on our end.

**Comment by OpenSkyPlus** [comment] 2024-07-13 15:10
Closing this as the issuedoesn't seem related to the plugin, but GSPro

**Closed by OpenSkyPlus** 2024-07-13 15:10 UTC
